//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcuraServicosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvaliacaoItem()
        {
            this.Avaliacao = new HashSet<Avaliacao>();
        }
    
        public int Id { get; set; }
        public int id_itemavaliacaocategoria { get; set; }
        public int id_usuario { get; set; }
        public int nota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliacao> Avaliacao { get; set; }
        public virtual ItemAvaliacaoCategoria ItemAvaliacaoCategoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
