//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcuraServicosWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avaliacao> Avaliacao { get; set; }
        public virtual DbSet<AvaliacaoItem> AvaliacaoItem { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Conta> Conta { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<ItemAvaliacaoCategoria> ItemAvaliacaoCategoria { get; set; }
        public virtual DbSet<PF> PF { get; set; }
        public virtual DbSet<PJ> PJ { get; set; }
        public virtual DbSet<Promocao> Promocao { get; set; }
        public virtual DbSet<RecomendacaoUsuario> RecomendacaoUsuario { get; set; }
        public virtual DbSet<Servico_Categoria> Servico_Categoria { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
    }
}
