//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcuraServicosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int id { get; set; }
        public int id_conta { get; set; }
        public int numero { get; set; }
        public string tiponumero { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
